services:
  redis:
    image: redis:7-alpine
    container_name: dietguard-redis
    ports:
      - "6376:6379"
    command: redis-server --requirepass myredissecret
    volumes:
      - redis_data:/data
    networks:
      - dietguard-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dietguard-backend
    ports:
      - "8010:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=myredissecret
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    volumes:
      - ./backend:/app
    networks:
      - dietguard-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://15.207.68.194:8010
        - REACT_APP_DOMAIN=15.207.68.194:3003
    container_name: dietguard-frontend
    ports:
      - "3003:3000"
    environment:
      - REACT_APP_API_URL=http://15.207.68.194:8010
      - REACT_APP_DOMAIN=15.207.68.194:3003
    depends_on:
      - backend
    networks:
      - dietguard-network

volumes:
  redis_data:

networks:
  dietguard-network:
    driver: bridge